### ISSUE TITLE
Arrays of GuidReferences can't be set individually from the Inspector.

### ISSUE THREAD

**Issue by LuaMeyer** [EmreDogann/unity-guid-reference#3]
When assigning a GuidReferences from the inspector, all array elements are set to the same reference.

https://github.com/EmreDogann/unity-guid-reference/assets/86572156/c389c39e-d983-49fd-8cdf-edc896713ae2

**Comment by EmreDogann** [comment]
I have put in a fix for this as well as GuidReference for components not working with lists in version 1.0.5. Please give it a try :)

Will close this issue for now. If you find that the latest version still doesn't completely fix this, then we can reopen this issue.

**Comment by LuaMeyer** [comment]
Thank you for the fast fix. It works now for my intended use case. :]
